import Footer from "@/components/Footer";
import PurpleBackground from "@/components/PurpleBackground";
import { Grid } from "@mui/material";
import Head from "next/head";
import Article from "./component/Article";
import Banner from "./component/Banner";
import Blog from "./component/Blog";
import StorageService from "./component/StorageService";
import TrendingProduct from "./component/TrendingProduct";
import Welcome from "./component/Welcome";
import Service from "./component/Service";
import Soulution from "./component/Solution";
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Home',
    description: ' EPIONEER Home Page',
}

const Home = () => {
    return (
        <Grid xs={12} container>
            <Head>
                <title>Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Grid xs={12} container>
                <PurpleBackground />
                <Grid item xs={12}>
                    <Banner />
                </Grid>
                <Grid item xs={12}>
                    <Welcome />
                </Grid>
                <Grid item xs={12}>
                    <TrendingProduct />
                </Grid>
                <Grid item xs={12}>
                    <Service />
                </Grid>
                <Grid item xs={12}>
                    <StorageService />
                </Grid>
                <Grid item xs={12}>
                    <Article />
                </Grid>
                <Grid item xs={12}>
                    <Blog />
                </Grid>
                <Grid item xs={12}>
                    <Soulution />
                </Grid>
            </Grid>
            <Grid xs={12}>
                <Footer />
            </Grid>
        </Grid>
    );
};

export default Home;
