import { Grid } from '@mui/material';
import type { Metadata } from 'next';
import Header from '@/components/Header';
import { Suspense } from 'react';
import Loading from './loading';

export const metadata: Metadata = {
    title: 'Main',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            <Suspense fallback={<Loading />}>
                <Grid item xs={12} sx={{ marginTop: '145px' }}>
                    {children}
                </Grid>
            </Suspense>
        </>
    );
}
